-- CREATE TABLE NEwTab(ID NUMBER PRIMARY KEY, NAME VARCHAR(20));
-- CREATE SEQUENCE MY_SEQ START WITH 1111 increment by 10; 

-- CREATE TABLE CIasda(ID_a NUMBER PRIMARY KEY, CONSTRAINT ABC FOREIGN KEY (ID_a) REFERENCES NEwTab(ID), NAME VARCHAR(20));


-- SELECT * FROM USER_CONSTRAINTS;
-- SELECT * FROM USEr_TABLES;
-- SELECT * FRoM USER_SEQUENCES;
 
-- DROP TABLE NEwTab;

SET SERVEROUTPUT ON
/
DECLARE
    CURSOR CUR_CONSTRAINTS IS SELECT TABLE_NAME, CONSTRAINT_NAME FROM USER_CONSTRAINTS;
    CURSOR CUR_SEQ IS SELECT SEQUENCE_NAME FROM USER_SEQUENCES; 
    CURSOR CUR_TABLES IS SELECT TABLE_NAME FROM USER_TABLES;
    
    V_COUNT_SEQ NUMBER := 0;
    V_COUNT_CONSTRAINTS NUMBER := 0;
    V_COUNT_TABLES NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_COUNT_SEQ FROM USER_SEQUENCES; 
    SELECT COUNT(*) INTO V_COUNT_CONSTRAINTS FROM USER_CONSTRAINTS;
    SELECT COUNT(*) INTO V_COUNT_TABLES FROM USER_TABLES;
    
    DBMS_OUTPUT.PUT_LINE('Sequences Present : ' || V_COUNT_SEQ || chr(10) || 'Tables Present :  ' ||  V_COUNT_TABLES || chr(10) || 'Constraints Present : ' || V_COUNT_CONSTRAINTS);
    
    IF V_COUNT_SEQ > 0 THEN
        FOR SEQ IN CUR_SEQ LOOP
            EXECUTE IMMEDIATE ('DROP SEQUENCE ' || SEQ.SEQUENCE_NAME );
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('SEQUENCES DROPPED');
    END IF;
        
    IF V_COUNT_CONSTRAINTS > 0 THEN
        FOR CONS IN CUR_CONSTRAINTS LOOP
            EXECUTE IMMEDIATE('ALTER TABLE ' || CONS.TABLE_NAME || ' DROP CONSTRAINT ' || CONS.CONSTRAINT_NAME);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('CONSTRATINTS DROPPED');
    END IF;
        
    IF V_COUNT_TABLES > 0 THEN
        FOR TABLESS IN CUR_TABLES LOOP
            EXECUTE IMMEDIATE('DROP TABLE ' || TABLESS.TABLE_NAME);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('TABLES DROPPED');
    END IF;
END; 
/

-- CREATING FIRST TABLE AND SEQUENCE
CREATE SEQUENCE SEQ_USER_ID
START WITH 2023100001
INCREMENT BY 1
CACHE 10;

-- CREATING USER_DETAILS TABLE
CREATE TABLE user_details (
    user_id           NUMBER NOT NULL,
    first_name        VARCHAR2(200 CHAR) NOT NULL,
    last_name         VARCHAR2(200 CHAR),
    email             VARCHAR2(200 CHAR) NOT NULL,
    street_address    VARCHAR2(200 CHAR) NOT NULL,
    city              VARCHAR2(200 CHAR) NOT NULL,
    country           VARCHAR2(200 CHAR) NOT NULL,
    states            VARCHAR2(200 CHAR) NOT NULL,
    zipcode           NUMBER NOT NULL, 
    age               NUMBER NOT NULL
);

-- ADDING  CONSTRATINTS TO USER_DETAILS
ALTER TABLE user_details ADD CONSTRAINT user_details_pk PRIMARY KEY ( user_id );