SET SERVEROUTPUT ON
/
CREATE OR REPLACE PROCEDURE ROLE_CREATION_PROCEDURE
AS
    CURSOR CUR_ROLES IS SELECT ROLE FROM DBA_ROLES WHERE ROLE LIKE 'SWASTH_%';

    E_ROLES_ABSENT EXCEPTION;
    
    V_COUNT_ROLES NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT_ROLES FROM DBA_ROLES WHERE ROLE LIKE 'SWASTH_%';
    
    IF V_COUNT_ROLES > 0 THEN
        FOR ROL IN CUR_ROLES LOOP
            EXECUTE IMMEDIATE ('DROP ROLE ' || ROL.ROLE); 
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('ROLES DROPPED');
    ELSE
        RAISE E_ROLES_ABSENT;
    END IF;

EXCEPTION
    WHEN E_ROLES_ABSENT THEN
        DBMS_OUTPUT.PUT_LINE('NO ROLES PRESENT... CREATING ROLES');
        EXECUTE IMMEDIATE ('CREATE ROLE SWASTH_ADMIN');
        EXECUTE IMMEDIATE ('CREATE ROLE SWASTH_EVENT_MANAGER');
        EXECUTE IMMEDIATE ('CREATE ROLE SWASTH_CLIENT');
        DBMS_OUTPUT.PUT_LINE('CREATED REQUIRED ROLES');
END ROLE_CREATION_PROCEDURE;
