SET SERVEROUTPUT ON
/
CREATE OR REPLACE PROCEDURE ROLE_CREATION_PROCEDURE
AS
    CURSOR CUR_ROLES IS SELECT ROLE FROM DBA_ROLES WHERE ROLE LIKE 'SWASTH_%';

    E_ROLES_ABSENT EXCEPTION;
    
    V_COUNT_ROLES NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT_ROLES FROM DBA_ROLES WHERE ROLE LIKE 'SWASTH_%';
    
    IF V_COUNT_ROLES > 0 THEN
        FOR ROL IN CUR_ROLES LOOP
            EXECUTE IMMEDIATE ('DROP ROLE ' || ROL.ROLE); 
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('ROLES DROPPED');
    ELSE
        RAISE E_ROLES_ABSENT;
    END IF;

EXCEPTION
    WHEN E_ROLES_ABSENT THEN
        DBMS_OUTPUT.PUT_LINE('NO ROLES PRESENT... CREATING ROLES');
        EXECUTE IMMEDIATE ('CREATE ROLE SWASTH_ADMIN');
        EXECUTE IMMEDIATE ('CREATE ROLE SWASTH_EVENT_MANAGER');
        EXECUTE IMMEDIATE ('CREATE ROLE SWASTH_CLIENT');
        DBMS_OUTPUT.PUT_LINE('CREATED REQUIRED ROLES');
END ROLE_CREATION_PROCEDURE;

-- Granting permissions for SWASTH_ADMIN role
GRANT INSERT, UPDATE, DELETE ON user_details TO SWASTH_ADMIN;
GRANT INSERT, UPDATE, DELETE ON sleep_details TO SWASTH_ADMIN;
GRANT INSERT, UPDATE, DELETE ON sleep_metrics TO SWASTH_ADMIN;
GRANT INSERT, UPDATE, DELETE ON exercise_details TO SWASTH_ADMIN;
GRANT INSERT, UPDATE, DELETE ON exercise_metrics TO SWASTH_ADMIN;
GRANT INSERT, UPDATE, DELETE ON health_details TO SWASTH_ADMIN;
GRANT INSERT, UPDATE, DELETE ON body_composition TO SWASTH_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON user_details TO SWASTH_ADMIN;


-- Granting permissions for SWASTH_EVENT_MANAGER role
GRANT SELECT ON user_details TO SWASTH_EVENT_MANAGER;
GRANT SELECT ON sleep_details TO SWASTH_EVENT_MANAGER;
GRANT SELECT ON sleep_metrics TO SWASTH_EVENT_MANAGER;
GRANT SELECT ON exercise_details TO SWASTH_EVENT_MANAGER;
GRANT SELECT ON exercise_metrics TO SWASTH_EVENT_MANAGER;
GRANT SELECT ON health_details TO SWASTH_EVENT_MANAGER;
GRANT SELECT ON body_composition TO SWASTH_EVENT_MANAGER;

-- Granting permissions for SWASTH_CLIENT role
GRANT SELECT ON user_details TO SWASTH_CLIENT;
GRANT SELECT ON sleep_details TO SWASTH_CLIENT;
GRANT SELECT ON sleep_metrics TO SWASTH_CLIENT;
GRANT SELECT ON exercise_details TO SWASTH_CLIENT;
GRANT SELECT ON exercise_metrics TO SWASTH_CLIENT;
GRANT SELECT ON health_details TO SWASTH_CLIENT;
GRANT SELECT ON body_composition TO SWASTH_CLIENT;

-- Granting access to views
GRANT SELECT ON health_progress_view TO SWASTH_CLIENT;
GRANT SELECT ON exercise_view TO SWASTH_CLIENT;
GRANT SELECT ON sleep_view TO SWASTH_CLIENT;
GRANT SELECT ON activities_view TO SWASTH_CLIENT;
GRANT SELECT ON user_overview TO SWASTH_CLIENT;