-- 1
CREATE TABLE EMP (
    EMPLOYEE_ID NUMBER PRIMARY KEY, 
    fNAme VARCHAR(250) NOT NULL, 
    lName VARCHAR(250) NOT NULL, 
    DEPT_ID NUMBER, 
    HIRE_DATE DATE NOT NULL , 
    SALARY NUMBER, 
    FOREIGN KEY (DEPT_ID) REFERENCES DEPT(DEPT_ID)

);


CREATE TABLE DEPT(
    DEPT_ID  NUMBER PRIMARY KEY, 
    DEPT_NAME VARCHAR(100) NOT NULL
);

SELECT * FROm EMP; 

SELECT * FROm DEPT; 


INSERT INTO DEPT VALUES(10, 'IT');
INSERT INTO DEPT VALUES(20, 'HR');
INSERT INTO DEPT VALUES(30, 'Finance');
INSERT INTO DEPT VALUES(40, 'Marketing');
INSERT INTO DEPT VALUES(50, 'Sales');


INSERT INTO EMp VALUES (101, 'john', 'doe', 10, TO_DATE('10-1-2020', 'DD-MM-YYYY'), 6000);
INSERT INTO EMp VALUES (102, 'jane', 'smith', 20, TO_DATE('15-02-2021', 'DD-MM-YYYY'), 8000);
INSERT INTO EMp VALUES (103, 'mike', 'brown', 20, TO_DATE('22-07-2020', 'DD-MM-YYYY'), 5500);
INSERT INTO EMp VALUES (104, 'susan', 'davis', 10, TO_DATE('01-11-2019', 'DD-MM-YYYY'), 5000);
INSERT INTO EMp VALUES (105, 'robert', 'wilson', 30, TO_DATE('19-04-2022', 'DD-MM-YYYY'), 7000);

-- 2
SELECT Fname, lname, salary, dept_name from ( 
SELECT E.FName, E.LName, E.salary, rank() over(PARTITION  BY D.DEPT_ID ORDER BY E.SALARY DESC) as rnk, D.dept_NAME FROM EMP E LEFT JOIn DEPT D ON D.DEPT_ID = E.DEPT_ID
)A WHERE  A.rnk = 1 ORDER BY A.SALARY DESC;

--3 
SELECT D.DEPT_ID, D.DEPT_NAME, AVG(E.SALARY) as AVG_SALARY, count(E.EMPLOYEE_ID) AS COUNT_OF_EMPLOYEES
FROM DEPT D
LEFT JOIN EMP E ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID, D.DEPT_NAME
ORDER BY AVG_SALARY ;

--4
SELECT 
    fName,
    lName,
    TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12) || ' Years ' || TRUNC(MOD(MONTHS_BETWEEN(SYSDATE, HIRE_DATE), 12)) || ' Months ' AS TENURE
FROM EMP
ORDER BY HIRE_DATE DESC;



--5 
SELECT e.fName, e.lName, e.SALARY, d.DEPT_NAME
FROM EMP e
JOIN DEPT d ON e.DEPT_ID = d.DEPT_ID
WHERE e.SALARY > (
    SELECT AVG(SALARY)
    FROM EMP
    WHERE DEPT_ID = e.DEPT_ID
)
ORDER BY e.DEPT_ID, e.SALARY DESC;

