CREATE USER ASSIGNMENT_FIVE_IND IDENTIFIED BY iamrootuser1Oracle;

GRANT CREATE SESSION TO ASSIGNMENT_FIVE_IND;

GRANT CONNECT TO ASSIGNMENT_FIVE_IND;

GRANT CREATE TABLE TO ASSIGNMENT_FIVE_IND;

GRANT DELETE TABLE To ASSIGNMENT_FIVE_IND;

GRANT UNLIMITED TABLESPACE TO ASSIGNMENT_FIVE_IND;

GRANT CONNECT, RESOURCE TO ASSIGNMENT_FIVE_IND;



