

CREATE USER ASSIGNMENT_SIX_IND IDENTIFIED BY iamrootuser1Oracle;

GRANT CREATE SESSION TO ASSIGNMENT_SIX_IND;

GRANT CONNECT TO ASSIGNMENT_SIX_IND;

GRANT CREATE TABLE TO ASSIGNMENT_SIX_IND;

GRANT UNLIMITED TABLESPACE TO ASSIGNMENT_SIX_IND;

GRANT CONNECT, RESOURCE TO ASSIGNMENT_SIX_IND;
