-- QUESTION 2

SELECT * FROM DEPT;
SELECT * FROM SALGRADE;
SELECT * FROM EMP;

-- 1)
SELECT D.DNAME, E.SumSal/E.EmpCount as avg FROM 
    (
        SELECT SUM(SAL) as SumSal, COUNT(EMPNO) as EmpCount, DEPTNO 
        FROM EMP 
        GROUP BY DEPTNO
    ) 
E LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO ORDER BY E.SumSal DESC
FETCH FIRST 5 ROWS ONLY;
    
    
    
--2)
SELECT * FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP);


--3)
SELECT * FROM(SELECT * FROM EMP E LEFT JOIN 
    (SELECT TO_CHAR(A.HIREDATE, 'YYYY') as Year, To_CHAR(A.HIREDATE, 'MM') as Month 
    FROM  (SELECT HIREDATE FROM EMP WHERE ENAME = 'SCOTT') A) AB
    ON E.ENAME != 'SCOTT') Final 
WHERE TO_CHAR(Final.HIREDATE, 'YYYY') = Final.Year AND To_CHAR(Final.HIREDATE, 'MM') = Final.Month;


--4)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.DEPTNO, E.SAL 
FROM EMP E LEFT JOIN 
    (SELECT AVG(SAL) as avg, DEPTNO FROM EMP GROUP BY DEPTNO) 
A  ON A.DEPTNO = E.DEPTNo 
WHERE E.SAL > A.avg;


--5)
SELECT A.Total_Employees, A.DEPTNO, A.Rank  
FROM 
    (SELECT Count(*) over () as tc, COUNT(EMPNO) as Total_Employees, DEPTNO, 
    RANK() over (ORDER BY COUNT(EMPNO)) as Rank 
    FROM EMP GROUP BY DEPTNO) A 
WHERE A.Rank = 1 OR Rank = A.tc; 


