SELECT * FROM emp;

SELECT *
FROM (
    SELECT DEPTNO, COUNT(*) AS NUM_EMPLOYEES
    FROM emp
    GROUP BY DEPTNO
)
PIVOT (
    MAX(NUM_EMPLOYEES)
    FOR DEPTNO IN (10 AS "DEPT_10", 20 AS "DEPT_20", 30 AS "DEPT_30", 40 AS "DEPT_40")
);


--2
WITH dept10 as (
SELECT COUNT(DEPTNO) as cnt FROM EMP WHERE DEPTNO = 10
),
 dept20 as (
SELECT COUNT(DEPTNO) as cnt FROM EMP WHERE DEPTNO = 20
),
 dept30 as (
SELECT COUNT(DEPTNO) as cnt FROM EMP WHERE DEPTNO = 30
)
SELECT dept10.cnt as DEPT_10, dept20.cnt as DEPT_20, dept30.cnt as "DEPT_30" FROM dept10, dept20, dept30;



-- 3
WITH a as (
    SELECT EMPNO, ENAME FROM EMP
)
SELECT E.EMPNO, E.ENAME, E.MGR, A.ENAME FROM EMP E LEFT JOIN A ON A.EMPNO = E.MGR;  

--4
SELECT * FROm EMP;