-- SELECT COUNT(SHIPPER_ID) as COUNT_OF_SHIPPERS FROM SHIPPERS;

-- SELECT FIRSTNAME AS FirstName, LASTNAME as LastName, HIREDATE as HireDate
-- FROM EMPLOYEES 
-- WHERE TITLE = 'Sales Representative' AND COUNTRY = 'USA';

-- SELECT O.ORDER_ID, O.CUSTOMER_ID, E.EMPLOYEE_ID, O.ORDER_DATE, O.SHIP_NAME, O.SHIP_ADDRESS, O.SHIP_CITY
-- FROM ORDERS O LEFT JOIN EMPLOYEES E  ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
-- WHERE E.LASTNAME ='Buchanan' and E.FIRSTNAME = 'Steven';

-- SELECT SUPPLIER_ID, CONTACT_NAME, CONTACT_TITLE 
-- FROM SUPPLIERS
-- WHERE CONTACT_TITLE != 'Marketing Manager';

-- SELECT PRODUCT_ID, PRODUCT_NAME 
-- FROM PRODUCTS
-- WHERE lower(PRODUCT_NAME) LIKE '%queso%';

-- SELECT ORDER_ID, CUSTOMER_ID, SHIP_COUNTRY
-- FROM ORDERS
-- WHERE UPPER(SHIP_COUNTRY) in ('BRAZIL', 'MEXICO', 'ARGENTINA', 'VENEZUELA', 'FRANCE', 'BELGIUM');

-- SELECT FIRSTNAME, LASTNAME, TITLE , BIRTHDATE
-- FROM EMPLOYEES
-- ORDER BY BIRTHDATE;

--  SELECT COUNT(CUSTOMER_ID) as TOTAL_CUSTOMERS FROM CUSTOMERS;


--  SELECT P.PRODUCT_ID, P.PRODUCT_NAME, S.COMPANY_NAME
-- FROM PRODUCTS P LEFT JOIN SUPPLIERS S ON P.SUPPLIER_ID = S.SUPPLIER_ID
-- ORDER BY P.PRODUCT_ID

-- SELECT CATEGORY_ID, COUNT(PRODUCT_ID) 
-- FROM PRODUCTS
-- GROUP BY CATEGORY_ID


-- SELECT COUNTRY, CITY, COUNT(EMPLOYEE_ID)
-- FROM EMPLOYEES
-- GROUP BY COUNTRY, CITY


-- SELECT newJoin.ORDER_ID, newJoin.PRODUCT_ID, newJoin.PRODUCT_NAME, newJoin.EMPLOYEE_ID, E.LASTNAME, newJoin.QUANTITY
-- FROM
-- (
--     SELECT temp.PRODUCT_ID, temp.ORDER_ID, temp.PRODUCT_NAME, OD.EMPLOYEE_ID, temp.QUANTITY  FROM
--     (
--         SELECT P.PRODUCT_ID, O.ORDER_ID, P.PRODUCT_NAME, O.QUANTITY
--         FROM PRODUCTS P LEFT JOIN ORDER_DETAILS O
--         ON P.PRODUCT_ID = O.PRODUCT_ID
--     ) temp LEFT JOIN ORDERS OD
--     ON temp.ORDER_ID = OD.ORDER_ID
-- )
-- newJoin LEFT JOIN EMPLOYEES E
-- ON newJoin.EMPLOYEE_ID = E.EMPLOYEE_ID
-- ORDER BY newJoin.ORDER_ID, PRODUCT_ID

-- SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM ORDERS)
